from typing import Protocol

class ICacheRepository(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl_seconds: int) -> None: ...
    async def incr(self, key: str) -> int: ...          # used for the viewport-cache epoch
    async def getdel(self, key: str) -> str | None: ...
