from dataclasses import dataclass
from typing import Protocol, Sequence
from uuid import UUID
from snapland.core.domain.area import Area, AreaVersion
from snapland.core.domain.user import User, Session

@dataclass(frozen=True)
class AreaPage:
    areas: Sequence[Area]
    truncated: bool            # True when more than `limit` areas matched the viewport

class IAreaReadRepository(Protocol):
    async def get_by_id(self, area_id: UUID) -> Area | None: ...
    async def get_within_bounds(
        self, min_lng: float, min_lat: float, max_lng: float, max_lat: float,
        *, zoom: int | None = None, limit: int = 500,
    ) -> AreaPage: ...
    async def get_version_history(self, area_id: UUID) -> Sequence[AreaVersion]: ...

class IAreaRepository(IAreaReadRepository, Protocol):
    # create / update / soft_delete write the area_versions row (and the audit row,
    # when an audit entry is supplied) in the SAME transaction as the area row.
    async def create(self, area: Area) -> Area: ...
    async def update(self, area: Area, expected_version: int) -> Area | None: ...   # None = version mismatch
    async def soft_delete(self, area_id: UUID, deleted_by: UUID) -> bool: ...

class IUserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def create(self, user: User) -> User: ...

class ISessionRepository(Protocol):
    """Refresh-token sessions. Rotation keeps the old row (revoked_at set) so reuse can be detected."""
    async def create(self, session: Session) -> Session: ...
    async def get_by_token_hash(self, token_hash: str) -> Session | None: ...
    async def revoke(self, session_id: UUID) -> None: ...
    async def revoke_family(self, family_id: UUID) -> int: ...
    async def revoke_all_for_user(self, user_id: UUID) -> int: ...
