import os
from pathlib import Path
import shutil

base_dir = Path(r"D:\AICode\snapland")

directories = [
    "backend/src/snapland/api/v1/websocket",
    "backend/src/snapland/core/interfaces",
    "backend/src/snapland/core/services",
    "backend/src/snapland/core/domain",
    "backend/src/snapland/infrastructure/db/repositories",
    "backend/src/snapland/infrastructure/cache",
    "backend/src/snapland/infrastructure/pubsub",
    "backend/src/snapland/infrastructure/jobs",
    "backend/src/snapland/middleware",
    "backend/migrations/versions",
    "backend/tests/unit/core",
    "backend/tests/unit/api",
    "backend/tests/unit/infrastructure",
    "backend/tests/integration",
    "frontend/src/api/interfaces",
    "frontend/src/api/http",
    "frontend/src/api/mock",
    "frontend/src/providers",
    "frontend/src/pages",
    "frontend/src/components/map",
    "frontend/src/components/ui",
    "frontend/src/components/auth",
    "frontend/src/hooks",
    "frontend/src/services/websocket",
    "frontend/src/services/map",
    "frontend/src/store",
    "frontend/src/types",
    "frontend/src/utils",
    "frontend/tests/unit/hooks",
    "frontend/tests/unit/services",
    "frontend/tests/unit/utils",
    "frontend/tests/e2e",
    "packages/shared-types/src/generated",
    "docs/adr",
    "docs/api",
    "infra/nginx",
    "infra/monitoring/grafana",
    "loadtest",
    "scripts",
    ".github/workflows"
]

for d in directories:
    (base_dir / d).mkdir(parents=True, exist_ok=True)

# create __init__.py for all python dirs
for root, dirs, files in os.walk(base_dir / "backend/src/snapland"):
    with open(os.path.join(root, "__init__.py"), "w") as f:
        pass

files_to_touch = [
    "backend/src/snapland/api/v1/auth.py",
    "backend/src/snapland/api/v1/areas.py",
    "backend/src/snapland/api/v1/users.py",
    "backend/src/snapland/api/v1/health.py",
    "backend/src/snapland/api/v1/websocket/route.py",
    "backend/src/snapland/api/v1/websocket/manager.py",
    "backend/src/snapland/api/v1/websocket/handlers.py",
    "backend/src/snapland/core/interfaces/repositories.py",
    "backend/src/snapland/core/interfaces/services.py",
    "backend/src/snapland/core/interfaces/cache.py",
    "backend/src/snapland/core/interfaces/realtime.py",
    "backend/src/snapland/core/services/area_service.py",
    "backend/src/snapland/core/services/auth_service.py",
    "backend/src/snapland/core/services/spatial_service.py",
    "backend/src/snapland/core/services/conflict_service.py",
    "backend/src/snapland/core/services/audit_service.py",
    "backend/src/snapland/core/domain/area.py",
    "backend/src/snapland/core/domain/user.py",
    "backend/src/snapland/core/domain/events.py",
    "backend/src/snapland/core/domain/ws_messages.py",
    "backend/src/snapland/infrastructure/db/models.py",
    "backend/src/snapland/infrastructure/db/session.py",
    "backend/src/snapland/infrastructure/db/repositories/base.py",
    "backend/src/snapland/infrastructure/db/repositories/area_repository.py",
    "backend/src/snapland/infrastructure/db/repositories/user_repository.py",
    "backend/src/snapland/infrastructure/db/repositories/session_repository.py",
    "backend/src/snapland/infrastructure/cache/redis_client.py",
    "backend/src/snapland/infrastructure/cache/cache_repository.py",
    "backend/src/snapland/infrastructure/pubsub/redis_pubsub.py",
    "backend/src/snapland/infrastructure/pubsub/redis_streams.py",
    "backend/src/snapland/infrastructure/pubsub/redis_presence.py",
    "backend/src/snapland/infrastructure/jobs/retention.py",
    "backend/src/snapland/middleware/rate_limiter.py",
    "backend/src/snapland/middleware/request_id.py",
    "backend/src/snapland/middleware/error_handler.py",
    "backend/src/snapland/middleware/metrics.py",
    "backend/src/snapland/middleware/timeout.py",
    "backend/src/snapland/config.py",
    "backend/migrations/env.py",
    "backend/tests/unit/core/test_area_service.py",
    "backend/tests/unit/core/test_spatial_service.py",
    "backend/tests/unit/core/test_auth_service.py",
    "backend/tests/unit/core/test_conflict_service.py",
    "backend/tests/unit/api/test_outbound_queue.py",
    "backend/tests/unit/api/test_ws_handlers.py",
    "backend/tests/unit/infrastructure/test_rate_limiter.py",
    "backend/tests/integration/test_areas_api.py",
    "backend/tests/integration/test_auth_api.py",
    "backend/tests/integration/test_websocket.py",
    "backend/tests/integration/test_presence.py",
    "backend/tests/integration/test_spatial_queries.py",
    "backend/tests/conftest.py",
    "backend/pyproject.toml",
    "backend/Dockerfile",
    "backend/README.md",
    "frontend/src/api/interfaces/IAreaApi.ts",
    "frontend/src/api/interfaces/IAuthApi.ts",
    "frontend/src/api/interfaces/IWebSocketService.ts",
    "frontend/src/api/http/areaApi.ts",
    "frontend/src/api/http/authApi.ts",
    "frontend/src/api/mock/mockAreaApi.ts",
    "frontend/src/api/mock/mockWebSocketService.ts",
    "frontend/src/providers/ApiProvider.tsx",
    "frontend/src/pages/LoginPage.tsx",
    "frontend/src/pages/MapPage.tsx",
    "frontend/src/components/map/MapView.tsx",
    "frontend/src/components/map/DrawingLayer.tsx",
    "frontend/src/components/map/VertexEditor.tsx",
    "frontend/src/components/map/CollaborationLayer.tsx",
    "frontend/src/components/map/AreaOverlay.tsx",
    "frontend/src/components/map/BaseLayerControl.tsx",
    "frontend/src/components/ui/AreaPanel.tsx",
    "frontend/src/components/ui/AreaList.tsx",
    "frontend/src/components/ui/AreaDetails.tsx",
    "frontend/src/components/ui/UserPresenceBar.tsx",
    "frontend/src/components/ui/ConflictDialog.tsx",
    "frontend/src/components/auth/LoginForm.tsx",
    "frontend/src/components/auth/RegisterForm.tsx",
    "frontend/src/hooks/useWebSocket.ts",
    "frontend/src/hooks/useMapBounds.ts",
    "frontend/src/hooks/useDrawing.ts",
    "frontend/src/hooks/useAreas.ts",
    "frontend/src/hooks/useAuth.ts",
    "frontend/src/services/websocket/WebSocketService.ts",
    "frontend/src/services/map/LayerManager.ts",
    "frontend/src/services/map/ProjectionUtils.ts",
    "frontend/src/store/areasStore.ts",
    "frontend/src/store/collaborationStore.ts",
    "frontend/src/store/authStore.ts",
    "frontend/src/utils/geoUtils.ts",
    "frontend/src/utils/areaCalculation.ts",
    "frontend/tests/unit/hooks/useDrawing.test.ts",
    "frontend/tests/unit/hooks/useWebSocket.test.ts",
    "frontend/tests/unit/services/LayerManager.test.ts",
    "frontend/tests/unit/utils/geoUtils.test.ts",
    "frontend/tests/unit/utils/areaCalculation.test.ts",
    "frontend/tests/e2e/drawing.spec.ts",
    "frontend/tests/e2e/layer-switch.spec.ts",
    "frontend/tests/e2e/collaboration.spec.ts",
    "frontend/tests/e2e/auth.spec.ts",
    "frontend/package.json",
    "frontend/vite.config.ts",
    "frontend/tsconfig.json",
    "frontend/Dockerfile",
    "frontend/README.md",
    "packages/shared-types/src/area.ts",
    "packages/shared-types/src/websocket.ts",
    "packages/shared-types/src/auth.ts",
    "packages/shared-types/src/geo.ts",
    "packages/shared-types/package.json",
    "docs/adr/001-postgis-choice.md",
    "docs/adr/002-redis-pubsub-and-streams.md",
    "docs/adr/003-occ-conflict.md",
    "docs/adr/004-projections-and-satellite-source.md",
    "docs/performance.md",
    "infra/docker-compose.yml",
    "infra/docker-compose.test.yml",
    "infra/nginx/nginx.conf",
    "infra/monitoring/prometheus.yml",
    "loadtest/ws_collab.js",
    "scripts/setup.sh",
    "scripts/seed_db.py",
    "scripts/gen_types.py",
    ".env.example",
    ".github/workflows/ci.yml",
    "README.md"
]

for file in files_to_touch:
    path = base_dir / file
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.touch()

# Copy HLD
shutil.copy(base_dir / "snapland-hld.md", base_dir / "docs/hld.md")
